name: first workflow
on: push
jobs:
  first-job:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 
      - name: install openshift client
        uses: redhat-actions/oc-installer@v1
        with:
          version: '4.7'
      - name: authenticate and set context
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USERNAME: ${{ secrets.OPENSHIFT_USERNAME }}
          OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: login to openshift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }} --insecure-skip-tls-verify=true
      - name: deploy to openshift
        run: mvn install -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.route.expose=true -Dquarkus.kubernetes-client.trust-certs=true

